# Generated by Django 5.0.2 on 2024-03-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('ApplicantID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Resume', models.FileField(upload_to='')),
                ('ProficiencyLevel', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('JobDescription', models.CharField(max_length=100)),
                ('OpenDate', models.DateField()),
                ('CloseDate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewDate', models.DateTimeField()),
                ('Rating', models.IntegerField()),
                ('Comments', models.TextField()),
            ],
            options={
                'db_table': 'performance_review',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('RecruitmentApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('ApplicationDate', models.DateTimeField()),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'recruitment_application',
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('HRID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='profilepics/')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('HireDate', models.DateTimeField()),
                ('Role', models.CharField(max_length=100)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.department')),
            ],
            options={
                'db_table': 'hr',
            },
        ),
    ]
