# Generated by Django 5.0.2 on 2024-03-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('SkillID', models.AutoField(primary_key=True, serialize=False)),
                ('SkillName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('DesignationID', models.AutoField(primary_key=True, serialize=False)),
                ('DesignationTitle', models.CharField(max_length=100)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.department')),
            ],
            options={
                'db_table': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='profilepics/')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('HireDate', models.DateTimeField()),
                ('BasicSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.department')),
                ('DesignationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.designation')),
                ('SkillID', models.ManyToManyField(to='EmployeeApp.skill')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('TotalHours', models.TimeField()),
                ('Status', models.CharField(max_length=100)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('LeaveID', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveType', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Status', models.CharField(max_length=100)),
                ('Comments', models.TextField()),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
            options={
                'db_table': 'Leave',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('PayrollID', models.AutoField(primary_key=True, serialize=False)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateField()),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
    ]
