# Generated by Django 5.0.2 on 2024-03-20 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
        ('ManagerApp', '0003_project_projectlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=100)),
                ('EventDescription', models.TextField()),
                ('EventPriority', models.CharField(max_length=100)),
                ('EventDate', models.DateTimeField()),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.manager')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('ScheduledEventID', models.AutoField(primary_key=True, serialize=False)),
                ('ScheduledEventName', models.CharField(max_length=255)),
                ('ScheduledEventDescription', models.CharField(max_length=255, null=True)),
                ('ScheduledEventPriority', models.CharField(max_length=255)),
                ('ScheduledEventDate', models.DateTimeField()),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.manager')),
            ],
            options={
                'db_table': 'ScheduledEvent',
            },
        ),
    ]
