# Generated by Django 5.0.2 on 2024-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_employee_password_employee_username_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='notes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
