# Generated by Django 5.0.2 on 2024-03-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_scheduledevent_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='notes',
        ),
    ]
