# Generated by Django 5.0.2 on 2024-03-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_remove_scheduledevent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TotalHours',
            field=models.TimeField(null=True),
        ),
    ]
