# Generated by Django 5.0.2 on 2024-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_alter_attendance_totalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
