# Generated by Django 5.0.2 on 2024-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
