# Generated by Django 5.0.2 on 2024-03-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='profilepics/')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='RemovalRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('RequestDate', models.DateTimeField()),
                ('Status', models.CharField(max_length=100)),
                ('Comments', models.TextField()),
            ],
            options={
                'db_table': 'removal_request',
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionDescription', models.TextField()),
                ('ActionDate', models.DateTimeField()),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.admin')),
            ],
            options={
                'db_table': 'admin_action_log',
            },
        ),
        migrations.CreateModel(
            name='AdminEmployeeRemovalLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('RemovalReason', models.TextField()),
                ('RemovalDate', models.DateTimeField()),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.admin')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
            options={
                'db_table': 'admin_employee_removal_log',
            },
        ),
        migrations.CreateModel(
            name='AdminManagerRemovalLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('RemovalReason', models.TextField()),
                ('RemovalDate', models.DateTimeField()),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.admin')),
            ],
            options={
                'db_table': 'admin_manager_removal_log',
            },
        ),
    ]
