# Generated by Django 5.0.2 on 2024-03-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('EmployeeApp', '0001_initial'),
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmanagerremovallog',
            name='ManagerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.manager'),
        ),
        migrations.AddField(
            model_name='removalrequest',
            name='ManagerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.manager'),
        ),
        migrations.AddField(
            model_name='removalrequest',
            name='TargetUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee'),
        ),
    ]
