# Generated by Django 5.0.2 on 2024-03-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeeApp', '0001_initial'),
        ('HrApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ManagerID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='profilepics/')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('HireDate', models.DateTimeField()),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.department')),
                ('DesignationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.designation')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.manager')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=100)),
                ('TaskDescription', models.TextField()),
                ('CloseDate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('RecruitmentType', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('HRID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HrApp.hr')),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.manager')),
                ('SkillID', models.ManyToManyField(to='EmployeeApp.skill')),
            ],
            options={
                'db_table': 'recruitment_request',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Status', models.CharField(max_length=100)),
                ('Priority', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField()),
                ('DueDate', models.DateTimeField()),
                ('CompletionDate', models.DateTimeField()),
                ('Comments', models.TextField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.project')),
                ('SkillID', models.ManyToManyField(to='EmployeeApp.skill')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=100)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.task')),
                ('TeamLead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('TeamMemberID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=100)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.team')),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
    ]
