# Generated by Django 5.0.2 on 2024-03-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='CompletionDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Status',
        ),
        migrations.AddField(
            model_name='project',
            name='DueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Priority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
